name: flutter_marti_lopez_entrga_final_abalit
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  provider: ^6.1.5

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lib/images/function_app_logo.png
    - lib/images/function_app_logo_cut.png
  fonts:
    - family: Onest
      fonts:
        - asset: lib/fonts/Onest-VariableFont_wght.ttf

    - family: PPEiko
      fonts:
        - asset: lib/fonts/PPEiko-LightItalic.otf
